name = "test"
author = "test"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a0647459afc4aff0d2ee0bbd025c9b332a2249502cda3cd2dcec2969eee3e3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21", "1.21.7"]
